[server]
maxUploadSize = 25

[theme]
primaryColor = "#00796B"  # Teal
backgroundColor = "#ECEFF1"  # Light Grey
secondaryBackgroundColor = "#FFFFFF"  # White
textColor = "#263238"  # Dark Grey
font = "monospace"

